### ISSUE TITLE
mongoengine.connection.ConnectionError: Cannot connect to database default

### ISSUE THREAD

**Issue by dvdme** [allisson/flask-example#2]
I got this error when running run.py

```
(flask-example) C:\Users\David\python-ninja\flask-example>python run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    app = create_app('settings')
  File "C:\Users\David\python-ninja\flask-example\application.py", line 20, in create_app
    db.init_app(app)
  File "c:\Users\David\python-ninja\flask-example\lib\site-packages\flask_mongoengine\__init__.py", line 66, in init_app
    self.connection = mongoengine.connect(**conn_settings)
  File "c:\Users\David\python-ninja\flask-example\lib\site-packages\mongoengine\connection.py", line 164, in connect
    return get_connection(alias)
  File "c:\Users\David\python-ninja\flask-example\lib\site-packages\mongoengine\connection.py", line 126, in get_connection
    raise ConnectionError("Cannot connect to database %s :\n%s" % (alias, e))
mongoengine.connection.ConnectionError: Cannot connect to database default :
False is not a read preference.
```

I fixed it by adding to settings.py
```
from pymongo import read_preferences
```
and
```
'read_preference': read_preferences.ReadPreference.PRIMARY
```
to MONGODB_SETTINGS.

**Comment by rohitsakala** [comment]
+1

**Comment by allisson** [comment]
Get the latest commit and test again.

**Comment by oleong** [comment]
hi
I have the same error
where do you put the MONGODB_SETTINGS?
and 'read_preference': read_preferences.ReadPreference.PRIMARY?
